In [49]:
import numpy as np
import pandas as pd

In [ ]:

df = pd.read_csv("data/weatherHistory.csv", index=)
df.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.

In [51]:
df.describe()

,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars)
count,96453.000000,96453.000000,96453.000000,96453.000000,96453.000000,96453.000000,96453.0,96453.000000
mean,11.932678,10.855029,0.734899,10.810640,187.509232,10.347325,0.0,1003.235956
std,9.551546,10.696847,0.195473,6.913571,107.383428,4.192123,0.0,116.969906
min,-21.822222,-27.716667,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
25%,4.688889,2.311111,0.600000,5.828200,116.000000,8.339800,0.0,1011.900000
50%,12.000000,12.000000,0.780000,9.965900,180.000000,10.046400,0.0,1016.450000
75%,18.838889,18.838889,0.890000,14.135800,290.000000,14.812000,0.0,1021.090000
max,39.905556,39.344444,1.000000,63.852600,359.000000,16.100000,0.0,1046.380000

In [52]:
df.isnull().sum()

Formatted Date                0
Summary                       0
Precip Type                 517
Temperature (C)               0
Apparent Temperature (C)      0
Humidity                      0
Wind Speed (km/h)             0
Wind Bearing (degrees)        0
Visibility (km)               0
Loud Cover                    0
Pressure (millibars)          0
Daily Summary                 0
dtype: int64

In [53]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 96453 entries, 0 to 96452
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Formatted Date            96453 non-null  str
 1   Summary                   96453 non-null  str
 2   Precip Type               95936 non-null  str
 3   Temperature (C)           96453 non-null  float64
 4   Apparent Temperature (C)  96453 non-null  float64
 5   Humidity                  96453 non-null  float64
 6   Wind Speed (km/h)         96453 non-null  float64
 7   Wind Bearing (degrees)    96453 non-null  float64
 8   Visibility (km)           96453 non-null  float64
 9   Loud Cover                96453 non-null  float64
 10  Pressure (millibars)      96453 non-null  float64
 11  Daily Summary             96453 non-null  str
dtypes: float64(8), str(4)
memory usage: 8.8 MB

In [54]:
df["Precip Type"] = df["Precip Type"].fillna(df["Precip Type"].mode()[0])

Applying imputation to column "Precip Type" as it is catagorical values to remove the missing values

In [55]:
df.isnull().sum()

Formatted Date              0
Summary                     0
Precip Type                 0
Temperature (C)             0
Apparent Temperature (C)    0
Humidity                    0
Wind Speed (km/h)           0
Wind Bearing (degrees)      0
Visibility (km)             0
Loud Cover                  0
Pressure (millibars)        0
Daily Summary               0
dtype: int64

Handled all the missing values

In [56]:
df["Formatted Date"] = pd.to_datetime(df["Formatted Date"], utc=True) 

df["Formatted Date"].dt.day

0        31
1        31
2         1
3         1
4         1
         ..
96448     9
96449     9
96450     9
96451     9
96452     9
Name: Formatted Date, Length: 96453, dtype: int32

In [ ]:
df["year"] =df["Formatted Date"].dt.year
df["month"] = df["Formatted Date"].dt.month
df["date"] = df["Formatted Date"].dt.day

In [60]:
df.drop("Formatted Date", inplace=True, axis=1)
df.head()

,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary,year,month,date
0,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.,2006,3,31
1,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.,2006,3,31
2,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.,2006,4,1
3,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.,2006,4,1
4,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.,2006,4,1

In [61]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 96453 entries, 0 to 96452
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Summary                   96453 non-null  str
 1   Precip Type               96453 non-null  str
 2   Temperature (C)           96453 non-null  float64
 3   Apparent Temperature (C)  96453 non-null  float64
 4   Humidity                  96453 non-null  float64
 5   Wind Speed (km/h)         96453 non-null  float64
 6   Wind Bearing (degrees)    96453 non-null  float64
 7   Visibility (km)           96453 non-null  float64
 8   Loud Cover                96453 non-null  float64
 9   Pressure (millibars)      96453 non-null  float64
 10  Daily Summary             96453 non-null  str
 11  year                      96453 non-null  int32
 12  month                     96453 non-null  int32
 13  date                      96453 non-null  int32
dtypes: float64(8), int32(3), str(3)
memory usage: 9.2 MB

In [62]:
categorical_col = df.select_dtypes(include=['str', 'object']).columns.to_list()
categorical_col

['Summary', 'Precip Type', 'Daily Summary']

In [ ]:
for col in categorical_col:
    print(df[col].mode())

0    Partly Cloudy
Name: Summary, dtype: str
0    rain
Name: Precip Type, dtype: str
0    Mostly cloudy throughout the day.
Name: Daily Summary, dtype: str

Categorical values do not provide any insight as it has only one values throughtout the dataset. Hence it is safe to remove these columns

In [67]:
df.drop(categorical_col, inplace=True, axis=1)
df.head()

,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),year,month,date
0,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,2006,3,31
1,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,2006,3,31
2,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,2006,4,1
3,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,2006,4,1
4,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,2006,4,1

In [68]:
df.to_csv("data/cleaned-data.csv")

## Summary 

1. Missing values handled
2. categorical values handled

Read for model training